## 1. Parse all links from Wikipedia xml dump

In [1]:
import xml.etree.ElementTree as etree
import codecs
import csv
import time
import os
import re
import gzip
import pandas as pd
import numpy as np

In [2]:
PATH_WIKI_XML = '/media/andrii/earth/Katia/CS_MasterThesis/BabelNet_baseline/uk-en_redlinks/data/ukwiki_20180920/'
PATH_WIKI_OUT = '/media/andrii/earth/Katia/CS_MasterThesis/BabelNet_baseline/uk-en_redlinks/data/ukwiki_20180920/'

In [3]:
PATH_TO_DATA = '/media/andrii/earth/Katia/CS_MasterThesis/BabelNet_baseline/uk-en_redlinks/data/ukwiki_20180920/'
data_time = '20180920'

In [4]:
def unpack(file_name):
    file_name_new = file_name.replace(".gz","")
    with gzip.open(file_name, 'rb') as f_in, open(file_name_new, 'wb') as f_out:
        f_out.writelines(f_in)
    return file_name_new

In [5]:
def pack_and_remove(file_name):
    file_name_new = file_name+'.gz'
    with open(file_name, 'rb') as f_in, gzip.open(file_name_new, 'wb') as f_out:
        f_out.writelines(f_in)
    os.remove(file_name)
    return file_name_new

In [6]:
WIKI_FILENAMES = []
for file in os.listdir(PATH_WIKI_XML):
    if file.endswith("pages-meta-current.xml"):
        WIKI_FILENAMES.append(file)
print(WIKI_FILENAMES)

['ukwiki-20180920-pages-meta-current.xml']

In [ ]:
ENCODING = "utf-8"


# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


def strip_tag_name(t):
    t = elem.tag
    idx = k = t.rfind("}")
    if idx != -1:
        t = t[idx + 1:]
    return t


totalCount = 0
articleCount = 0
redirectCount = 0
total_article_text_len = 0

In [ ]:
start_time = time.time()
regex_links = re.compile(r"\[\[(?P<article>(?!.*?\:).*?)(?:\{\{.*\}\})?(?:\|(?P<text>(?!.*?\:).*?))?\]\]")
for WikiXML in WIKI_FILENAMES:
    pathWikiXML = os.path.join(PATH_WIKI_XML, WikiXML)
    pathArticles = os.path.join(PATH_WIKI_OUT, WikiXML+"_art.csv")
    pathArticlesRedirect = os.path.join(PATH_WIKI_OUT, WikiXML+"_red.csv")
    with codecs.open(pathArticles, "w", ENCODING) as articlesFH, \
    codecs.open(pathArticlesRedirect, "w", ENCODING) as redirectFH:
        articlesWriter = csv.writer(articlesFH, quoting=csv.QUOTE_MINIMAL)
        articlesWriter.writerow(['id', 'title', 'text_len', 'link_pos', 'link_val', 'link_txt']) 
        redirectWriter = csv.writer(redirectFH, quoting=csv.QUOTE_MINIMAL)
        redirectWriter.writerow(['id', 'title', 'redirect'])
        for event, elem in etree.iterparse(pathWikiXML, events=('start', 'end')):
            tname = strip_tag_name(elem.tag)

            if event == 'start':
                if tname == 'page':
                    title = ''
                    id = -1
                    redirect = ''
                    inrevision = False
                    ns = 0
                    article_text_len = 0
                    links = []
                elif tname == 'revision':
                    # Do not pick up on revision id's
                    inrevision = True
            else:
                if tname == 'title':
                    title = elem.text
                elif tname == 'id' and not inrevision:
                    id = int(elem.text)
                elif tname == 'redirect':
                    redirect = elem.attrib['title']
                elif tname == 'ns':
                    ns = int(elem.text)
                elif tname == 'page' and ns == 0:
                    totalCount += 1
                        
                    if len(redirect) == 0:
                        articleCount += 1
                        total_article_text_len += article_text_len
                        if len(links) == 0:
                            articlesWriter.writerow([id, title, article_text_len, 0, "", ""])
                        for link in links:
                            articlesWriter.writerow([id, title, article_text_len, link[0], link[1], link[2]])
                    else:
                        redirectCount += 1
                        redirectWriter.writerow([id, title, redirect])

                    if totalCount > 1 and (totalCount % 100000) == 0:
                        print("{:,}".format(totalCount))
                elif tname == 'text' and elem.text != None:
                    article_text_len = len(elem.text)
                    for match in regex_links.finditer(elem.text):    
                        link_pos = match.start()
                        link_title = match.group("article")
                        link_title = link_title.replace("&nbsp;", " ")
                        link_title = link_title.replace("&ndash;", "-")
                        link_title = link_title.replace("&mdash;", "—")
                        link_title = link_title.replace("%20", " ")
                        
                        link_text = match.group("text")
                        links.append((link_pos,link_title,link_text))


                elem.clear()
    
    fn_in = pathArticles
    with open(fn_in, 'rb') as f_in, gzip.open(fn_in+'.gz', 'wb') as f_out:
        f_out.writelines(f_in)
    os.remove(fn_in)
    
    fn_in = pathArticlesRedirect
    with open(fn_in, 'rb') as f_in, gzip.open(fn_in+'.gz', 'wb') as f_out:
        f_out.writelines(f_in)
    os.remove(fn_in)
    
    elapsed_time = time.time() - start_time
    print("File processed: {}".format(WikiXML))
    print("Total pages: {:,}".format(totalCount))
    print("Article pages: {:,}".format(articleCount))
    print("Redirect pages: {:,}".format(redirectCount))
    print("Total article lenght: {:,}".format(total_article_text_len))
    print("Elapsed time: {}".format(hms_string(elapsed_time)))

elapsed_time = time.time() - start_time

print("Total pages: {:,}".format(totalCount))
print("Article pages: {:,}".format(articleCount))
print("Redirect pages: {:,}".format(redirectCount))
print("Total article lenght: {:,}".format(total_article_text_len))
print("Elapsed time: {}".format(hms_string(elapsed_time)))

In [ ]:
### results in two csv.gz files - with articles and redirections

In [7]:
df_articles = pd.read_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-pages-meta-current.xml_red.csv.gz", encoding='UTF-8', quotechar="\"")

In [8]:
df_articles.head()

    id                 title                            redirect
0    2             Esperanto                           Есперанто
1    6             Wikipedia                           Вікіпедія
2    9              HomePage                    Головна сторінка
3  647     Капустянко Микола  Капустянський Микола Олександрович
4  693  Володимир Винниченко      Винниченко Володимир Кирилович

In [63]:
df_articles[df_articles['title']=='Католицтво']

             id       title           redirect
451080  2808027  Католицтво  Католицька церква

In [ ]:
# wrong parsing:
# 'Свідницький повіт (Нижньосілезьке воєводство){{!}}Свідницький повіт'
# japanese symbols

In [ ]:
# find where a bug - !redirections: 'католицизм', 'королева', 'ВВС Україна'...

# found:
# 'королева', 'Королева' not in redirection list - created after dump, was a red link then
# 'католицизм', 'ВВС Україна' - redirections to redirections

## 1.1 Remove redirections to redirections bug

In [9]:
df_articles = pd.read_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-pages-meta-current.xml_red.csv.gz",
                          encoding='UTF-8', quotechar="\"")
df_articles.head()

    id                 title                            redirect
0    2             Esperanto                           Есперанто
1    6             Wikipedia                           Вікіпедія
2    9              HomePage                    Головна сторінка
3  647     Капустянко Микола  Капустянський Микола Олександрович
4  693  Володимир Винниченко      Винниченко Володимир Кирилович

In [7]:
df_redirect1 = df_articles[['title']]
df_redirect1.columns = ['redirect']

In [8]:
df_redirect1.head()

               redirect
0             Esperanto
1             Wikipedia
2              HomePage
3     Капустянко Микола
4  Володимир Винниченко

In [9]:
df_redirect2 = df_articles[['redirect']]

In [10]:
df_redirect2.head()

                             redirect
0                           Есперанто
1                           Вікіпедія
2                    Головна сторінка
3  Капустянський Микола Олександрович
4      Винниченко Володимир Кирилович

In [11]:
frames = [df_redirect1, df_redirect2]
df_all_redirections = pd.concat(frames)

In [12]:
df_all_redirections

                                       redirect
0                                     Esperanto
1                                     Wikipedia
2                                      HomePage
3                             Капустянко Микола
4                          Володимир Винниченко
5                                    Белза Ігор
6                       Інформаційна технологія
7                                       Історик
8                      Міфологія давньої Греції
9                    Історія філософії в особах
10                                Леонід Глібов
11                                          США
12                    Perl programming language
13                                  C Plus Plus
14                                          WWW
15                            Економіка (наука)
16            Базова система введення/виведення
17                                 Гьодель Курт
18                          Список міст України
19                                          МОП
20                                    Main Page
21                                          ЕОМ
22                                      Педагог
23                        Список історичних дат
24        Дискретний простір елементарних подій
25                            Ймовірність події
26                         Перестановки множини
27                        Математичні константи
28                   Список столиць за країнами
29                               Євген Гребінка
...                                         ...
453518                                   Ґондув
453519                                   Ґондув
453520                              Боґдашовіце
453521                              Боґдашовіце
453522                              Боґдашовіце
453523                           Мокронос-Ґурни
453524                           Мокронос-Ґурни
453525                           Мокронос-Ґурни
453526                               Войтковіце
453527                             Стшеґановіце
453528                             Стшеґановіце
453529                             Стшеґановіце
453530                          Мокронос-Дольни
453531            Садовіце (Вроцлавський повіт)
453532                                  Кшептув
453533              Козлув (Вроцлавський повіт)
453534                        Нова Весь-Концька
453535   Кембловіце (Нижньосілезьке воєводство)
453536              Садкув (Вроцлавський повіт)
453537                                 Заховіце
453538             Малушув (Вроцлавський повіт)
453539     Журавіце (Нижньосілезьке воєводство)
453540                              Тинець-Мали
453541                              Щепанковіце
453542  Круліковіце (Нижньосілезьке воєводство)
453543                       Пусткув-Журавський
453544                       Пусткув-Журавський
453545    Добковіце (Нижньосілезьке воєводство)
453546      Яшовіце (Нижньосілезьке воєводство)
453547       Хшанув (Нижньосілезьке воєводство)

[907096 rows x 1 columns]

In [13]:
df_all_redirections = df_all_redirections.drop_duplicates()

In [14]:
df_all_redirections.shape

(723894, 1)

In [16]:
df_all_redirections.to_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-redirections.csv", 
                     index = False, encoding='UTF-8', quotechar="\"", sep ="^")

## 2. Get all article names

In [8]:
UKWIKI_ART_FNMS = []
for file in os.listdir(PATH_TO_DATA):
    if re.match(r"ukwiki-" + data_time + "-pages-meta-current.xml_art.csv.gz", file):
        UKWIKI_ART_FNMS.append(file)
print('UKWIKI_ART_FNMS:', UKWIKI_ART_FNMS)

UKWIKI_ART_FNMS: ['ukwiki-20180920-pages-meta-current.xml_art.csv.gz']

In [9]:
df_uk_id_name = None
for fn in UKWIKI_ART_FNMS:
    fn = PATH_TO_DATA+fn
    print(fn)
    fn_new = unpack(fn)
    df_articles = pd.read_csv(fn_new, encoding='UTF-8', quotechar="\"")
    print(df_articles.head(100))
    df_id_name_tmp = df_articles[['id', 'title', 'text_len']].drop_duplicates()
    df_id_name_tmp.columns = ['id', 'title', 'length']
    #print("df_id_name_tmp size: {}".format(df_id_name_tmp.shape))
    if df_uk_id_name is not None:
        df_uk_id_name = df_uk_id_name.append(df_id_name_tmp)        
        #print("append")
    else:
        df_uk_id_name = df_id_name_tmp
        #print("assign")
    print("df_uk_id_name size: {}".format(df_uk_id_name.shape))
    os.remove(fn_new)
df_uk_id_name = df_uk_id_name.drop_duplicates()

/media/andrii/earth/Katia/BabelNet_baseline/uk-en_redlinks/data/ukwiki-20180920-pages-meta-current.xml_art.csv.gz
     id             title  text_len  link_pos                        link_val  \
0     3  Головна сторінка      3197         0                             NaN
1    13         Географія     16843      1228              Об'єкт (філософія)
2    13         Географія     16843      1533                       Ератосфен
3    13         Географія     16843      1599                         географ
4    13         Географія     16843      1611                Клавдій Птолемей
5    13         Географія     16843      1722                     Відродження
6    13         Географія     16843      1797                        еллінізм
7    13         Географія     16843      1883                 Герард Меркатор
8    13         Географія     16843      1996        Александер фон Гумбольдт
9    13         Географія     16843      2047                     Карл Ріттер
10   13         Географія     16843      4559                історичний метод
11   13         Географія     16843      5907                 Науки про Землю
12   13         Географія     16843      5969                     картографія
13   13         Географія     16843      6366                    Біогеографія
14   13         Географія     16843      6386                    Кліматологія
15   13         Географія     16843      6406                    Метеорологія
16   13         Географія     16843      6426                  Берегознавство
17   13         Географія     16843      6448          Екологічний менеджмент
18   13         Географія     16843      6657                        Геодезія
19   13         Географія     16843      6673                   Геоморфологія
20   13         Географія     16843      6694                     Гляціологія
21   13         Географія     16843      6713                      Гідрологія
22   13         Географія     16843      6731                     Гідрографія
23   13         Географія     16843      6899             Ландшафтна екологія
24   13         Географія     16843      6926                    Океанографія
25   13         Географія     16843      6946                  Ґрунтознавство
26   13         Географія     16843      6968                  Палеогеографія
27   13         Географія     16843      7042            Четвертинна геологія
28   13         Географія     16843      7187                       літосфера
29   13         Географія     16843      7212                      гідросфера
..  ...               ...       ...       ...                             ...
70   13         Географія     16843     10412  Вернадський Володимир Іванович
71   13         Географія     16843     10600            Козлов Петро Кузьмич
72   13         Географія     16843     10683       Рудницький Степан Львович
73   13         Географія     16843     10776     Оппоков Євген Володимирович
74   13         Географія     16843     10868             Шмідт Отто Юлійович
75   13         Географія     16843     10972   Висоцький Георгій Миколайович
76   13         Географія     16843     11077          Фейгін Яків Григорович
77   13         Географія     16843     11213               географія ґрунтів
78   13         Географія     16843     11254      Погребняк Петро Степанович
79   13         Географія     16843     11338                   геоморфологія
80   13         Географія     16843     11371  Бондарчук Володимир Гаврилович
81   13         Географія     16843     11855  Удовиченко Вікторія Віталіївна
82   13         Географія     16843     15521                     Smithsonian
83  584              Атом     35112      1928                           гелій
84  584              Атом     35112      1995                      ядро атома
85  584              Атом     35112      2247               квантова механіка
86  584              Атом     35112      2358         Планетарна модель атома
87  584              Атом     35112      2421                Ернест Резерфорд
88  584              Атом     35112      2553              Атомна модель Бора
89  584              Атом     35112      2738                 Сонячна система
90  584              Атом     35112      2955           Джеймс Клерк Максвелл
91  584              Атом     35112      3133                     Прискорення
92  584              Атом     35112      3379                Хвильова функція
93  584              Атом     35112      3417             електронна орбіталь
94  584              Атом     35112      3597            елементарна частинка
95  584              Атом     35112      3645                          протон
96  584              Атом     35112      3659                        електрон
97  584              Атом     35112      3678                         нейтрон
98  584              Атом     35112      3921              Періодична система
99  584              Атом     35112      4006               електричний заряд

                        link_txt
0                            NaN
1                         Об'єкт
2                            NaN
3                            NaN
4                            NaN
5                            NaN
6                            NaN
7              Герарда Меркатора
8            Олександр Гумбольдт
9                            NaN
10                           NaN
11                           NaN
12                   картографію
13                           NaN
14                           NaN
15                           NaN
16                           NaN
17                           NaN
18                           NaN
19                           NaN
20                           NaN
21                           NaN
22                           NaN
23                           NaN
24                           NaN
25                           NaN
26                           NaN
27                           NaN
28                     літосферу
29                    гідросферу
..                           ...
70  В.&nbsp;І.&nbsp;Вернадського
71        П.&nbsp;К.&nbsp;Козлов
72    С.&nbsp;Л.&nbsp;Рудницький
73       Є.&nbsp;В.&nbsp;Оппоков
74         О.&nbsp;Ю.&nbsp;Шмідт
75     Г.&nbsp;М.&nbsp;Висоцький
76        Я.&nbsp;Г.&nbsp;Фейгін
77             географії ґрунтів
78     П.&nbsp;С.&nbsp;Погребняк
79                 геоморфології
80     В.&nbsp;Г.&nbsp;Бондарчук
81              Удовиченко В. В.
82                           NaN
83                         гелію
84                         ядром
85            квантової механіки
86            планетарної моделі
87          Ернестом Резерфордом
88                   моделі Бора
89               Сонячну систему
90                      Максвела
91                  прискоренням
92              Хвильові функції
93          орбіталей електронів
94         елементарних частинок
95                           NaN
96                           NaN
97                           NaN
98           періодичній системі
99                         заряд

[100 rows x 6 columns]
df_uk_id_name size: (819212, 3)

In [35]:
df_uk_id_name.to_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-id_name.csv", 
                     index = False, encoding='UTF-8', quotechar="\"", sep ="^")

## 4. Get links between all pages

In [10]:
df_uk_redirections = pd.read_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-redirections.csv", 
                            encoding='UTF-8', quotechar="\"", sep ="^")
df_uk_redirections.columns = ['title']
df_uk_redirections.head()

                  title
0             Esperanto
1             Wikipedia
2              HomePage
3     Капустянко Микола
4  Володимир Винниченко

In [11]:
print(df_uk_redirections.shape)

(723893, 1)

In [12]:
df_uk_id_name = pd.read_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-id_name.csv", 
                         encoding='UTF-8', quotechar="\"", sep ="^")

In [13]:
df_uk_name = df_uk_id_name[['title']]
df_uk_name.head()

              title
0  Головна сторінка
1         Географія
2              Атом
3           Мільярд
4              Ядро

In [14]:
frames = [df_uk_redirections, df_uk_name]
df_uk_name_all = pd.concat(frames)

In [15]:
df_uk_name_all['title'] = df_uk_name_all['title'].str.strip()

In [16]:
df_uk_name_all.head()

                  title
0             Esperanto
1             Wikipedia
2              HomePage
3     Капустянко Микола
4  Володимир Винниченко

In [17]:
df_uk_name_all_strip = df_uk_name_all.iloc[:,0]

In [18]:
df_uk_name_all_strip = df_uk_name_all_strip.str.replace('  ', ' ')

In [19]:
df_uk_name_all_stripped = df_uk_name_all_strip.to_frame()

In [20]:
df_uk_name_all_stripped.head()

                  title
0             Esperanto
1             Wikipedia
2              HomePage
3     Капустянко Микола
4  Володимир Винниченко

In [21]:
df_uk_name_all_stripped = df_uk_name_all_stripped.drop_duplicates()

In [22]:
df_uk_name_all.shape

(1543105, 1)

In [23]:
df_uk_name_all['title_lc'] = df_uk_name_all['title'].str.lower()

In [24]:
df_uk_name_all.head()

                  title              title_lc
0             Esperanto             esperanto
1             Wikipedia             wikipedia
2              HomePage              homepage
3     Капустянко Микола     капустянко микола
4  Володимир Винниченко  володимир винниченко

In [25]:
fn = PATH_TO_DATA+"ukwiki-" + data_time + "-pages-meta-current.xml_art.csv.gz"
print(fn)
fn_new = unpack(fn)
df_articles = pd.read_csv(fn_new, encoding='UTF-8', quotechar="\"")
df_articles['link_val'] = df_articles['link_val'].str.split("#").str[0] # ???
df_articles = df_articles[df_articles['link_val'].str.strip() != ''] 
df_articles.head(100)

/media/andrii/earth/Katia/CS_MasterThesis/BabelNet_baseline/uk-en_redlinks/data/ukwiki_20180920/ukwiki-20180920-pages-meta-current.xml_art.csv.gz

,id,title,text_len,link_pos,link_val,link_txt
0,3,Головна сторінка,3197,0,NaN,NaN
1,13,Географія,16843,1228,Об'єкт (філософія),Об'єкт
2,13,Географія,16843,1533,Ератосфен,NaN
3,13,Географія,16843,1599,географ,NaN
4,13,Географія,16843,1611,Клавдій Птолемей,NaN
5,13,Географія,16843,1722,Відродження,NaN
6,13,Географія,16843,1797,еллінізм,NaN
7,13,Географія,16843,1883,Герард Меркатор,Герарда Меркатора
8,13,Географія,16843,1996,Александер фон Гумбольдт,Олександр Гумбольдт
9,13,Географія,16843,2047,Карл Ріттер,NaN
10,13,Географія,16843,4559,історичний метод,NaN
11,13,Географія,16843,5907,Науки про Землю,NaN
12,13,Географія,16843,5969,картографія,картографію
13,13,Географія,16843,6366,Біогеографія,NaN
14,13,Географія,16843,6386,Кліматологія,NaN
15,13,Географія,16843,6406,Метеорологія,NaN
16,13,Географія,16843,6426,Берегознавство,NaN
17,13,Географія,16843,6448,Екологічний менеджмент,NaN
18,13,Географія,16843,6657,Геодезія,NaN
19,13,Географія,16843,6673,Геоморфологія,NaN
20,13,Географія,16843,6694,Гляціологія,NaN
21,13,Географія,16843,6713,Гідрологія,NaN
22,13,Географія,16843,6731,Гідрографія,NaN
23,13,Географія,16843,6899,Ландшафтна екологія,NaN
24,13,Географія,16843,6926,Океанографія,NaN
25,13,Географія,16843,6946,Ґрунтознавство,NaN
26,13,Географія,16843,6968,Палеогеографія,NaN
27,13,Географія,16843,7042,Четвертинна геологія,NaN
28,13,Географія,16843,7187,літосфера,літосферу
29,13,Географія,16843,7212,гідросфера,гідросферу
...,...,...,...,...,...,...
70,13,Географія,16843,10412,Вернадський Володимир Іванович,В.&nbsp;І.&nbsp;Вернадського
71,13,Географія,16843,10600,Козлов Петро Кузьмич,П.&nbsp;К.&nbsp;Козлов
72,13,Географія,16843,10683,Рудницький Степан Львович,С.&nbsp;Л.&nbsp;Рудницький
73,13,Географія,16843,10776,Оппоков Євген Володимирович,Є.&nbsp;В.&nbsp;Оппоков
74,13,Географія,16843,10868,Шмідт Отто Юлійович,О.&nbsp;Ю.&nbsp;Шмідт
75,13,Географія,16843,10972,Висоцький Георгій Миколайович,Г.&nbsp;М.&nbsp;Висоцький
76,13,Географія,16843,11077,Фейгін Яків Григорович,Я.&nbsp;Г.&nbsp;Фейгін
77,13,Географія,16843,11213,географія ґрунтів,географії ґрунтів
78,13,Географія,16843,11254,Погребняк Петро Степанович,П.&nbsp;С.&nbsp;Погребняк
79,13,Географія,16843,11338,геоморфологія,геоморфології
80,13,Географія,16843,11371,Бондарчук Володимир Гаврилович,В.&nbsp;Г.&nbsp;Бондарчук
81,13,Географія,16843,11855,Удовиченко Вікторія Віталіївна,Удовиченко В. В.
82,13,Географія,16843,15521,Smithsonian,NaN
83,584,Атом,35112,1928,гелій,гелію
84,584,Атом,35112,1995,ядро атома,ядром
85,584,Атом,35112,2247,квантова механіка,квантової механіки
86,584,Атом,35112,2358,Планетарна модель атома,планетарної моделі
87,584,Атом,35112,2421,Ернест Резерфорд,Ернестом Резерфордом
88,584,Атом,35112,2553,Атомна модель Бора,моделі Бора
89,584,Атом,35112,2738,Сонячна система,Сонячну систему
90,584,Атом,35112,2955,Джеймс Клерк Максвелл,Максвела
91,584,Атом,35112,3133,Прискорення,прискоренням
92,584,Атом,35112,3379,Хвильова функція,Хвильові функції
93,584,Атом,35112,3417,електронна орбіталь,орбіталей електронів
94,584,Атом,35112,3597,елементарна частинка,елементарних частинок
95,584,Атом,35112,3645,протон,NaN
96,584,Атом,35112,3659,електрон,NaN
97,584,Атом,35112,3678,нейтрон,NaN
98,584,Атом,35112,3921,Періодична система,періодичній системі
99,584,Атом,35112,4006,електричний заряд,заряд

In [26]:
df_articles['title'] = df_articles['title'].str.strip()
df_articles['link_val'] = df_articles['link_val'].str.strip()

In [27]:
df_uk_titles_series = df_articles.iloc[:,4]

In [28]:
df_uk_titles_series_stripped = df_uk_titles_series.str.replace('  ', ' ')

In [29]:
df_titles_stripped = df_uk_titles_series_stripped.to_frame()

In [30]:
df_titles_stripped.head()

             link_val
0                 NaN
1  Об'єкт (філософія)
2           Ератосфен
3             географ
4    Клавдій Птолемей

In [31]:
df_titles_stripped['link_val'] = df_titles_stripped['link_val'].str.lower()

In [33]:
print(len(df_titles_stripped))
print(len(df_articles))

22650865
22650865

# Create files with page links

In [35]:
df_articles_with_lc = pd.concat([df_articles, df_titles_stripped], axis=1)

In [36]:
df_articles_with_lc.head()

,id,title,text_len,link_pos,link_val,link_txt,link_val
0,3,Головна сторінка,3197,0,NaN,NaN,NaN
1,13,Географія,16843,1228,Об'єкт (філософія),Об'єкт,об'єкт (філософія)
2,13,Географія,16843,1533,Ератосфен,NaN,ератосфен
3,13,Географія,16843,1599,географ,NaN,географ
4,13,Географія,16843,1611,Клавдій Птолемей,NaN,клавдій птолемей

In [95]:
df_uk_id_name = pd.read_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-id_name.csv", 
                         encoding='UTF-8', quotechar="\"", sep ="^")

In [96]:
df_uk_id_name = df_uk_id_name[['id', 'title']]

In [97]:
df_uk_id_name.head()

    id             title
0    3  Головна сторінка
1   13         Географія
2  584              Атом
3  585           Мільярд
4  586              Ядро

In [91]:
redirections = PATH_TO_DATA+'ukwiki-' + data_time + '-pages-meta-current.xml_red.csv.gz'
redirections = unpack(redirections)

In [92]:
df_uk_redirections = pd.read_csv(redirections, encoding='UTF-8', quotechar="\"")

In [93]:
df_uk_redirections = df_uk_redirections[['id', 'title']]

In [94]:
df_uk_redirections.head()

    id                 title
0    2             Esperanto
1    6             Wikipedia
2    9              HomePage
3  647     Капустянко Микола
4  693  Володимир Винниченко

In [98]:
df_all_ids_uk = pd.concat([df_uk_id_name, df_uk_redirections], axis=0)

In [99]:
df_all_ids_uk.head()

    id             title
0    3  Головна сторінка
1   13         Географія
2  584              Атом
3  585           Мільярд
4  586              Ядро

In [100]:
df_all_ids_uk.shape

(1272760, 2)

In [101]:
df_all_ids_uk['title'] = df_all_ids_uk['title'].str.strip()

df_all_ids_uk_series = df_all_ids_uk.iloc[:,1]

df_all_ids_uk_series_stripped = df_all_ids_uk_series.str.replace('  ', ' ')
df_all_ids_uk_stripped = df_all_ids_uk_series_stripped.to_frame()

df_all_ids_uk_stripped['title'] = df_all_ids_uk_stripped['title'].str.lower()

In [107]:
df_all_ids_uk_stripped.shape

(1272760, 1)

In [108]:
df_all_ids_uk_cleaned = pd.concat([df_all_ids_uk, df_all_ids_uk_stripped], axis=1)

In [113]:
df_all_ids_uk_cleaned.columns = ['id', 'title', 'title_lc']

In [114]:
df_all_ids_uk_cleaned.head()

    id             title          title_lc
0    3  Головна сторінка  головна сторінка
1   13         Географія         географія
2  584              Атом              атом
3  585           Мільярд           мільярд
4  586              Ядро              ядро

In [116]:
df_articles_with_lc.columns = ['id', 'title', 'text_len', 'link_pos', 'link_val', 'link_txt', 'link_val_lc']

In [117]:
df_articles_with_lc.head()

,id,title,text_len,link_pos,link_val,link_txt,link_val_lc
0,3,Головна сторінка,3197,0,NaN,NaN,NaN
1,13,Географія,16843,1228,Об'єкт (філософія),Об'єкт,об'єкт (філософія)
2,13,Географія,16843,1533,Ератосфен,NaN,ератосфен
3,13,Географія,16843,1599,географ,NaN,географ
4,13,Географія,16843,1611,Клавдій Птолемей,NaN,клавдій птолемей

In [119]:
page_links_dirty = pd.merge(df_articles_with_lc, df_all_ids_uk_cleaned, how='left', left_on=['link_val_lc'], right_on=['title_lc'])

In [121]:
page_links_dirty = page_links_dirty[pd.notnull(page_links_dirty['link_val'])]

In [135]:
page_links_dirty.head()

,id_x,title_x,text_len,link_pos,link_val,link_txt,link_val_lc,id_y,title_y,title_lc
3,13,Географія,16843,1228,Об'єкт (філософія),Об'єкт,об'єкт (філософія),884280.0,Об'єкт (філософія),об'єкт (філософія)
4,13,Географія,16843,1533,Ератосфен,NaN,ератосфен,21623.0,Ератосфен,ератосфен
5,13,Географія,16843,1599,географ,NaN,географ,274944.0,Географ,географ
6,13,Географія,16843,1611,Клавдій Птолемей,NaN,клавдій птолемей,26194.0,Клавдій Птолемей,клавдій птолемей
7,13,Географія,16843,1722,Відродження,NaN,відродження,20459.0,Відродження,відродження

In [136]:
page_links_with_titles = page_links_dirty[['id_x', 'title_x', 'id_y', 'link_val', 'title_lc']]

In [137]:
page_links_with_titles.head()

   id_x    title_x      id_y            link_val            title_lc
3    13  Географія  884280.0  Об'єкт (філософія)  об'єкт (філософія)
4    13  Географія   21623.0           Ератосфен           ератосфен
5    13  Географія  274944.0             географ             географ
6    13  Географія   26194.0    Клавдій Птолемей    клавдій птолемей
7    13  Географія   20459.0         Відродження         відродження

In [138]:
page_links_with_titles.to_csv(PATH_TO_DATA+'page_links_with_titles.csv', index = False, encoding='UTF-8', sep='^')

In [126]:
page_links_ids = page_links_with_titles[['id_x', 'id_y']]
page_links_ids.columns = ['id', 'link_id']

In [128]:
page_links_ids.to_csv(PATH_TO_DATA+'uk_page_links_ids.csv', index = False, encoding='UTF-8', sep='^')

In [129]:
# point red and blue links in page links

In [165]:
page_links_with_titles.head()

   id_x    title_x      id_y            link_val            title_lc
3    13  Географія  884280.0  Об'єкт (філософія)  об'єкт (філософія)
4    13  Географія   21623.0           Ератосфен           ератосфен
5    13  Географія  274944.0             географ             географ
6    13  Географія   26194.0    Клавдій Птолемей    клавдій птолемей
7    13  Географія   20459.0         Відродження         відродження

In [154]:
all_uk_redlinks_with_parent_ids = pd.read_csv(PATH_TO_DATA+'all_uk_redlinks_with_parent_ids.csv', encoding='UTF-8', quotechar="\"")

In [155]:
all_uk_redlinks_with_parent_ids = all_uk_redlinks_with_parent_ids[['red_link_name']]

In [158]:
all_uk_redlinks_with_parent_ids['red_link_name'] = all_uk_redlinks_with_parent_ids['red_link_name'].str.strip()

all_uk_redlinks_series = all_uk_redlinks_with_parent_ids.iloc[:,0]

all_uk_redlinks_series_stripped = all_uk_redlinks_series.str.replace('  ', ' ')
all_uk_redlinks_stripped = all_uk_redlinks_series_stripped.to_frame()

all_uk_redlinks_stripped['red_link_name'] = all_uk_redlinks_stripped['red_link_name'].str.lower()

In [162]:
all_uk_redlinks = all_uk_redlinks_stripped.drop_duplicates()

In [164]:
all_uk_redlinks.head()

                                 red_link_name
0                           географія розвитку
1                               географія часу
3                         туристична географія
4       рентгенівська спектроскопія поглинання
5  рентгенівська фото електронна спектроскопія

In [167]:
page_links_with_red = pd.merge(page_links_with_titles, all_uk_redlinks, how='left', left_on=['title_lc'], right_on=['red_link_name'])

In [ ]:
page_links_with_red

In [48]:
# find red links among all links
links_which_exist = pd.merge(df_uk_name_all, df_titles_stripped,
                             how='right', left_on=['title_lc'], right_on=['link_val'])

In [49]:
links_which_exist = links_which_exist.drop_duplicates()

In [50]:
links_which_exist = links_which_exist.dropna(how='all')

In [51]:
links_which_exist

,title,title_lc,link_val
0,Esperanto,esperanto,esperanto
2,Wikipedia,wikipedia,wikipedia
31,Володимир Винниченко,володимир винниченко,володимир винниченко
155,Белза Ігор,белза ігор,белза ігор
157,Інформаційна технологія,інформаційна технологія,інформаційна технологія
162,Історик,історик,історик
2772,Міфологія давньої Греції,міфологія давньої греції,міфологія давньої греції
2776,Леонід Глібов,леонід глібов,леонід глібов
2806,США,сша,сша
56900,WWW,www,www
56901,Www,www,www
56958,Економіка (наука),економіка (наука),економіка (наука)
56994,МОП,моп,моп
57009,ЕОМ,еом,еом
57235,Педагог,педагог,педагог
60508,Список історичних дат,список історичних дат,список історичних дат
60510,Ймовірність події,ймовірність події,ймовірність події
60513,Перестановки множини,перестановки множини,перестановки множини
60515,Математичні константи,математичні константи,математичні константи
60518,Євген Гребінка,євген гребінка,євген гребінка
60549,Іван Котляревський,іван котляревський,іван котляревський
60660,Кочерга Іван,кочерга іван,кочерга іван
60665,Пантелеймон Куліш,пантелеймон куліш,пантелеймон куліш
60803,Семенко Михайль,семенко михайль,семенко михайль
60807,Список історико-культурних заповідників України,список історико-культурних заповідників україни,список історико-культурних заповідників україни
60811,Європейський валютний союз,європейський валютний союз,європейський валютний союз
60813,ЄС,єс,єс
62071,ЄБРР,єбрр,єбрр
62107,Спілка письменників України,спілка письменників україни,спілка письменників україни
62108,Спілка Письменників України,спілка письменників україни,спілка письменників україни
...,...,...,...
34630790,NaN,NaN,lubiąż
34630791,NaN,NaN,pałac w żerkowie
34630792,NaN,NaN,каменний кар'єр
34630793,NaN,NaN,степне (глибоківський район)
34630794,NaN,NaN,хосе мозіню-да-сілвейра
34630795,NaN,NaN,генеральна рада (португалія)
34630796,NaN,NaN,фінал кубка австрії з футболу 1936
34630797,NaN,NaN,mirków (województwo dolnośląskie)
34630799,NaN,NaN,pasikurowice (przystanek kolejowy)
34630800,NaN,NaN,веселе (глибоківський район)
34630801,NaN,NaN,винне
34630802,NaN,NaN,горна ульбінка
34630803,NaN,NaN,нова ульба
34630804,NaN,NaN,топіха
34630805,NaN,NaN,ульба перевалочна
34630806,NaN,NaN,siedlec trzebnicki
34630807,NaN,NaN,spichlerz
34630808,NaN,NaN,калініно (глибоківський район)
34630809,NaN,NaN,електронна промисловість україни
34630810,NaN,NaN,pałac w świątnikach
34630811,NaN,NaN,білоусовка (глибоківський район)
34630813,NaN,NaN,білокаменка (глибоківський район)
34630814,NaN,NaN,новомихайловка (глибоківський район)
34630815,NaN,NaN,планідовка
34630816,NaN,NaN,pałac w krobielowicach
34630817,NaN,NaN,ochotnicza straż pożarna
34630818,NaN,NaN,kąty wrocławskie
34630819,NaN,NaN,bystrzyca (dopływ odry)
34630821,NaN,NaN,pałac w sadowicach
34630822,NaN,NaN,lundin petroleum ab

In [52]:
candidates_for_redlinks = links_which_exist[links_which_exist['title'].isnull()]

In [53]:
candidates_for_redlinks = candidates_for_redlinks[['link_val']]

In [54]:
candidates_for_redlinks.shape

(1532585, 1)

In [55]:
candidates_for_redlinks.head()

                                             link_val
31758551                           географія розвитку
31758552                               географія часу
31758555                         туристична географія
31758556       рентгенівська спектроскопія поглинання
31758557  рентгенівська фото електронна спектроскопія

In [56]:
candidates_for_redlinks[candidates_for_redlinks['link_val']=='москва ']

Empty DataFrame
Columns: [link_val]
Index: []

In [57]:
df_articles.head()

   id             title  text_len  link_pos            link_val link_txt
0   3  Головна сторінка      3197         0                 NaN      NaN
1  13         Географія     16843      1228  Об'єкт (філософія)   Об'єкт
2  13         Географія     16843      1533           Ератосфен      NaN
3  13         Географія     16843      1599             географ      NaN
4  13         Географія     16843      1611    Клавдій Птолемей      NaN

In [58]:
df_uk_titles_series = df_articles.iloc[:,4]

In [59]:
df_uk_titles_series_stripped = df_uk_titles_series.str.replace('  ', ' ')

In [60]:
df_titles_stripped = df_uk_titles_series_stripped.to_frame()

In [61]:
df_titles_stripped['link_val_lc'] = df_titles_stripped['link_val'].str.lower()

In [62]:
df_pagelinks_with_lowercase = pd.concat([df_articles, df_titles_stripped], axis=1)

In [63]:
df_pagelinks_with_lowercase_redlinks = pd.merge(df_pagelinks_with_lowercase, candidates_for_redlinks,
         how='left', left_on=['link_val_lc'], right_on=['link_val'])

In [64]:
df_pagelinks_with_lowercase_redlinks

,id,title,text_len,link_pos,link_val_x,link_txt,link_val_x,link_val_lc,link_val_y
0,3,Головна сторінка,3197,0,NaN,NaN,NaN,NaN,NaN
1,13,Географія,16843,1228,Об'єкт (філософія),Об'єкт,Об'єкт (філософія),об'єкт (філософія),NaN
2,13,Географія,16843,1533,Ератосфен,NaN,Ератосфен,ератосфен,NaN
3,13,Географія,16843,1599,географ,NaN,географ,географ,NaN
4,13,Географія,16843,1611,Клавдій Птолемей,NaN,Клавдій Птолемей,клавдій птолемей,NaN
5,13,Географія,16843,1722,Відродження,NaN,Відродження,відродження,NaN
6,13,Географія,16843,1797,еллінізм,NaN,еллінізм,еллінізм,NaN
7,13,Географія,16843,1883,Герард Меркатор,Герарда Меркатора,Герард Меркатор,герард меркатор,NaN
8,13,Географія,16843,1996,Александер фон Гумбольдт,Олександр Гумбольдт,Александер фон Гумбольдт,александер фон гумбольдт,NaN
9,13,Географія,16843,2047,Карл Ріттер,NaN,Карл Ріттер,карл ріттер,NaN
10,13,Географія,16843,4559,історичний метод,NaN,історичний метод,історичний метод,NaN
11,13,Географія,16843,5907,Науки про Землю,NaN,Науки про Землю,науки про землю,NaN
12,13,Географія,16843,5969,картографія,картографію,картографія,картографія,NaN
13,13,Географія,16843,6366,Біогеографія,NaN,Біогеографія,біогеографія,NaN
14,13,Географія,16843,6386,Кліматологія,NaN,Кліматологія,кліматологія,NaN
15,13,Географія,16843,6406,Метеорологія,NaN,Метеорологія,метеорологія,NaN
16,13,Географія,16843,6426,Берегознавство,NaN,Берегознавство,берегознавство,NaN
17,13,Географія,16843,6448,Екологічний менеджмент,NaN,Екологічний менеджмент,екологічний менеджмент,NaN
18,13,Географія,16843,6657,Геодезія,NaN,Геодезія,геодезія,NaN
19,13,Географія,16843,6673,Геоморфологія,NaN,Геоморфологія,геоморфологія,NaN
20,13,Географія,16843,6694,Гляціологія,NaN,Гляціологія,гляціологія,NaN
21,13,Географія,16843,6713,Гідрологія,NaN,Гідрологія,гідрологія,NaN
22,13,Географія,16843,6731,Гідрографія,NaN,Гідрографія,гідрографія,NaN
23,13,Географія,16843,6899,Ландшафтна екологія,NaN,Ландшафтна екологія,ландшафтна екологія,NaN
24,13,Географія,16843,6926,Океанографія,NaN,Океанографія,океанографія,NaN
25,13,Географія,16843,6946,Ґрунтознавство,NaN,Ґрунтознавство,ґрунтознавство,NaN
26,13,Географія,16843,6968,Палеогеографія,NaN,Палеогеографія,палеогеографія,NaN
27,13,Географія,16843,7042,Четвертинна геологія,NaN,Четвертинна геологія,четвертинна геологія,NaN
28,13,Географія,16843,7187,літосфера,літосферу,літосфера,літосфера,NaN
29,13,Географія,16843,7212,гідросфера,гідросферу,гідросфера,гідросфера,NaN
...,...,...,...,...,...,...,...,...,...
22650835,2817985,Яшовіце (Нижньосілезьке воєводство),2842,1046,SIMC,NaN,SIMC,simc,NaN
22650836,2817985,Яшовіце (Нижньосілезьке воєводство),2842,1186,Гміна Кобежице,гміні Кобежице,Гміна Кобежице,гміна кобежице,NaN
22650837,2817985,Яшовіце (Нижньосілезьке воєводство),2842,1220,Вроцлавський повіт,Вроцлавського повіту,Вроцлавський повіт,вроцлавський повіт,NaN
22650838,2817985,Яшовіце (Нижньосілезьке воєводство),2842,1264,Нижньосілезьке воєводство,Нижньосілезького воєводства,Нижньосілезьке воєводство,нижньосілезьке воєводство,NaN
22650839,2817985,Яшовіце (Нижньосілезьке воєводство),2842,1409,Адміністративний поділ Польщі в 1975-1998,У 1975-1998 роках,Адміністративний поділ Польщі в 1975-1998,адміністративний поділ польщі в 1975-1998,NaN
22650840,2817985,Яшовіце (Нижньосілезьке воєводство),2842,1490,Вроцлавське воєводство (1975–1998),Вроцлавського воєводства,Вроцлавське воєводство (1975–1998),вроцлавське воєводство (1975–1998),NaN
22650841,2817985,Яшовіце (Нижньосілезьке воєводство),2842,2235,Центральний статистичний офіс Польщі,GUS,Центральний статистичний офіс Польщі,центральний статистичний офіс польщі,NaN
22650842,2817985,Яшовіце (Нижньосілезьке воєводство),2842,2691,Центральний статистичний офіс Польщі,GUS,Центральний статистичний офіс Польщі,центральний статистичний офіс польщі,NaN
22650843,2817988,Хшанув (Нижньосілезьке воєводство),2833,27,Польща,NaN,Польща,польща,NaN
22650844,2817988,Хшанув (Нижньосілезьке воєводство),2833,382,Вроцлавський повіт,NaN,Вроцлавський повіт,вроцлавський повіт,NaN
22650845,2817988,Хшанув (Нижньосілезьке воєводство),2833,901,літній час,NaN,літній час,літній час,NaN
22650846,2817988,Хшанув (Нижньосілезьке воєводство),2833,1038,SIMC,NaN,SIMC,simc,NaN
22650847,2817988,Хшанув (Нижньосілезьке воєводство),2833,1176,Гміна Кобежице,гміні Кобежице,Гміна Кобежице,гміна кобежице,NaN
22650848,2817988,Хшанув (Нижньосілезьке воєводство),2833,1210,Вроцлавський повіт,Вроцлавського повіту,Вроцлавський повіт,вроцлавський повіт,NaN
22650849,2817988,Хшанув (Нижньосілезьке воєводство),2833,1254,Нижньосілезьке воєводство,Нижньосілезького воєводства,Нижньосілезьке воєводство,нижньосілезьке воєводство,NaN
22650850,2817988,Хшанув (Нижньосілезьке воєводство),2833,1399,Адміністративний поділ Польщі в 1975-1998,У 1975-1998 роках,Адміністративний поділ Польщі в 1975-1998,адміністративний поділ польщі в 1975-1998,NaN
22650851,2817988,Хшанув (Нижньосілезьке воєводство),2833,1480,Вроцлавське воєводство (1975–1998),Вроцлавського воєводства,Вроцлавське воєводство (1975–1998),вроцлавське воєводство (1975–1998),NaN
22650852,2817988,Хшанув (Нижньосілезьке воєводство),2833,2226,Центральний статистичний офіс Польщі,GUS,Центральний статистичний офіс Польщі,центральний статистичний офіс польщі,NaN
22650853,2817988,Хшанув (Нижньосілезьке воєводство),2833,2682,Центральний статистичний офіс Польщі,GUS,Центральний статистичний офіс Польщі,центральний статистичний офіс польщі,NaN
22650854,2817992,Беляни-Вроцлавські,3017,27,Польща,NaN,Польща,польща,NaN
22650855,2817992,Беляни-Вроцлавські,3017,452,Вроцлавський повіт,NaN,Вроцлавський повіт,вроцлавський повіт,NaN
22650856,2817992,Беляни-Вроцлавські,3017,972,літній час,NaN,літній час,літній час,NaN
22650857,2817992,Беляни-Вроцлавські,3017,1109,SIMC,NaN,SIMC,simc,NaN
22650858,2817992,Беляни-Вроцлавські,3017,1292,Гміна Кобежице,гміні Кобежице,Гміна Кобежице,гміна кобежице,NaN
22650859,2817992,Беляни-Вроцлавські,3017,1326,Вроцлавський повіт,Вроцлавського повіту,Вроцлавський повіт,вроцлавський повіт,NaN
22650860,2817992,Беляни-Вроцлавські,3017,1370,Нижньосілезьке воєводство,Нижньосілезького воєводства,Нижньосілезьке воєводство,нижньосілезьке воєводство,NaN
22650861,2817992,Беляни-Вроцлавські,3017,1517,Адміністративний поділ Польщі в 1975-1998,У 1975-1998 роках,Адміністративний поділ Польщі в 1975-1998,адміністративний поділ польщі в 1975-1998,NaN
22650862,2817992,Беляни-Вроцлавські,3017,1598,Вроцлавське воєводство (1975–1998),Вроцлавського воєводства,Вроцлавське воєводство (1975–1998),вроцлавське воєводство (1975–1998),NaN
22650863,2817992,Беляни-Вроцлавські,3017,2410,Центральний статистичний офіс Польщі,GUS,Центральний статистичний офіс Польщі,центральний статистичний офіс польщі,NaN
22650864,2817992,Беляни-Вроцлавські,3017,2866,Центральний статистичний офіс Польщі,GUS,Центральний статистичний офіс Польщі,центральний статистичний офіс польщі,NaN

In [65]:
redlinks_with_all = df_pagelinks_with_lowercase_redlinks[~(df_pagelinks_with_lowercase_redlinks['link_val_y'].isnull())]

In [66]:
redlinks = redlinks_with_all[['id', 'link_val_x']]
redlinks.columns = ['id', 'link_val', 'dd']

In [67]:
redlinks = redlinks[['id', 'link_val']]

In [68]:
redlinks.to_csv(PATH_TO_DATA+'ukwiki-20180920-all_reslinks.csv', index = False, encoding='UTF-8', quotechar="\"")

In [40]:
df_articles.to_csv(PATH_TO_DATA+'ukwiki-20180920-pages-links.csv.gz', index = False, encoding='UTF-8', quotechar="\"")

In [41]:
pack_and_remove(fn_new)

'/media/andrii/earth/Katia/BabelNet_baseline/uk-en_redlinks/data/ukwiki-20180920-pages-meta-current.xml_art.csv.gz'

## 5. Get En correspondences for Ukrainian articles

In [ ]:
# 1) convert sql dump into csv file  
# see https://stackoverflow.com/questions/27584405/how-to-import-a-mysqldump-into-pandas

from io import StringIO
import re, shutil
import os.path

reg1 = re.compile('`([\w_]+)`')
reg2 = re.compile(r'\((?P<val>\d+?,\'[a-z]*?\',\'.*?(?:(?:\\\\)|(?<!\\))\')\)')

FN_UK_LANGLINKS = 'ukwiki-20180920-langlinks.sql'
dump_filename = PATH_TO_DATA+FN_UK_LANGLINKS
target_table = "langlinks"

sio = StringIO()

read_mode = 0 # 0 - skip, 1 - header, 2 - data
with open(dump_filename, 'r', encoding='ISO-8859-1') as f:
    for line in f:
        line = line.strip()
        if line.lower().startswith('insert') and target_table in line:
            read_mode = 2
        if line.lower().startswith('create table') and target_table in line:
            read_mode = 1
            continue

        if read_mode==0:
            continue

        # Filling up the headers
        elif read_mode==1:
            if line.lower().startswith('primary'):
                # add more conditions here for different cases 
                #(e.g. when simply a key is defined, or no key is defined)
                read_mode=0
                sio.seek(sio.tell()-1) # delete last comma
                sio.write('\n')
                continue
            colheader = re.findall(reg1,line)
            for col in colheader:
                sio.write(col.strip())
                sio.write(',')

        # Filling up the data -same as @firelynx's code
        elif read_mode ==2:
            for match in reg2.finditer(line): 
                newline = match.group("val")
                #print(newline)
                newline = newline.strip(' ()')
                #print(newline)
                newline = newline.replace('`', '')
                #print(newline)
                sio.write(newline)
                sio.write("\n")
            #if line.endswith(';'):
                #print("END OF INSERT")
sio.seek(0)
with open (PATH_TO_DATA+'ukwiki-20180920-langlinks.csv', 'w', encoding='ISO-8859-1') as fd:
    shutil.copyfileobj(sio, fd,-1)

In [ ]:
df_uk_langlinks = pd.read_csv(PATH_TO_DATA+'ukwiki-20180920-langlinks.csv', encoding='ISO-8859-1', quotechar="'", escapechar ="\\")
df_uk_langlinks

In [ ]:
df_uk_en_langlinks = df_uk_langlinks[df_uk_langlinks.ll_lang == 'en']
df_uk_en_langlinks.shape

In [ ]:
df_uk_en_langlinks.to_csv(PATH_TO_DATA+'ukwiki-20180920-langlinks_en.csv', 
                     index = False, encoding='UTF-16', quotechar="\"", sep ="^")                          quotechar="'", escapechar ="\\", quoting=csv.QUOTE_NONNUMERIC)

In [ ]:
df_en_langlinks = pd.read_csv(PATH_TO_DATA+'ukwiki-20180920-langlinks_en.csv', encoding='UTF-16', sep="^")

In [ ]:
df_en_langlinks = df_en_langlinks[pd.notnull(df_en_langlinks['ll_title'])]
df_en_langlinks.head()

In [ ]:
df_en_langlinks.to_csv(PATH_TO_DATA + data_time + "-langlinks_uk_en.csv", index = False, 
                      encoding='ISO-8859-1', quotechar="'", 
                      escapechar ="\\", quoting=csv.QUOTE_NONNUMERIC)

In [6]:
df_uk_full = pd.read_csv(PATH_TO_DATA+'ukwiki-20180920-pages-links.csv')

In [42]:
df_articles.head()

   id  link_id            link_val is_red_link
3  13   884280  Об'єкт (філософія)       False
4  13    21623           Ератосфен       False
5  13   274944             географ       False
6  13    26194    Клавдій Птолемей       False
7  13    20459         Відродження       False

In [45]:
df_articles[df_articles['link_val']=='Католицизм']

               id  link_id    link_val is_red_link
46505        1083    10732  Католицизм       False
69128        1348    10732  Католицизм       False
110523       1600    10732  Католицизм       False
116834       1624    10732  Католицизм       False
126687       1692    10732  Католицизм       False
128672       1707    10732  Католицизм       False
137094       1765    10732  Католицизм       False
137236       1765    10732  Католицизм       False
137303       1765    10732  Католицизм       False
142457       1784    10732  Католицизм       False
146506       1814    10732  Католицизм       False
151370       3030    10732  Католицизм       False
161655       3126    10732  Католицизм       False
200853       3875    10732  Католицизм       False
215168       4120    10732  Католицизм       False
239035       4701    10732  Католицизм       False
264571       5280    10732  Католицизм       False
300231       6328    10732  Католицизм       False
303521       6389    10732  Католицизм       False
316418       6633    10732  Католицизм       False
359429       7142    10732  Католицизм       False
378099       7314    10732  Католицизм       False
381883       7342    10732  Католицизм       False
392065       7449    10732  Католицизм       False
436867       9622    10732  Католицизм       False
457941      10156    10732  Католицизм       False
465766      10190    10732  Католицизм       False
484464      10403    10732  Католицизм       False
484466      10403    10732  Католицизм       False
498118      10606    10732  Католицизм       False
...           ...      ...         ...         ...
17247723  2307656    10732  Католицизм       False
17280189  2313037    10732  Католицизм       False
17287197  2314416    10732  Католицизм       False
17302001  2317431    10732  Католицизм       False
17368270  2327557    10732  Католицизм       False
17411900  2333972    10732  Католицизм       False
17474384  2344905    10732  Католицизм       False
17560164  2356210    10732  Католицизм       False
17561445  2356425    10732  Католицизм       False
17806076  2389483    10732  Католицизм       False
17976954  2418658    10732  Католицизм       False
18081786  2438718    10732  Католицизм       False
18122716  2443804    10732  Католицизм       False
18190597  2450737    10732  Католицизм       False
20917611  2562145    10732  Католицизм       False
20954537  2568652    10732  Католицизм       False
21000711  2576321    10732  Католицизм       False
21063451  2590996    10732  Католицизм       False
21097948  2594866    10732  Католицизм       False
21299852  2617863    10732  Католицизм       False
21333830  2620998    10732  Католицизм       False
21355547  2623896    10732  Католицизм       False
21581614  2655560    10732  Католицизм       False
21675161  2670569    10732  Католицизм       False
21927271  2705775    10732  Католицизм       False
22241693  2756179    10732  Католицизм       False
22384412  2770245    10732  Католицизм       False
22420623  2775243    10732  Католицизм       False
22462551  2779061    10732  Католицизм       False
22682794  2809317    10732  Католицизм       False

[777 rows x 4 columns]

### Files needed for final processing:
### 1. 'ukwiki-20180920-pages-links.csv'
### 2. "ukwiki-" + data_time + "-id_name.csv"
### 3. '20180920-langlinks_uk_en.csv'
### 4. 'ukwiki-20180920-all_reslinks.csv'

In [69]:
df_uk_full = pd.read_csv(PATH_TO_DATA+'ukwiki-20180920-pages-links.csv')
print(df_uk_full.shape)
df_uk_full.head()

(22693778, 4)

   id  link_id            link_val is_red_link
0  13   884280  Об'єкт (філософія)       False
1  13    21623           Ератосфен       False
2  13   274944             географ       False
3  13    26194    Клавдій Птолемей       False
4  13    20459         Відродження       False

In [70]:
df_uk_blue = df_uk_full[df_uk_full['is_red_link']==False][['id','link_id']]

print('blue links:')
print(df_uk_blue.shape)
print(df_uk_blue.columns)
print()

blue links:
(19818824, 2)
Index(['id', 'link_id'], dtype='object')

In [71]:
df_uk_red = pd.read_csv(PATH_TO_DATA+'ukwiki-20180920-all_reslinks.csv', encoding='UTF-8', quotechar="\"")

In [72]:
df_uk_red.head()

    id                                     link_val
0   13                           Географія розвитку
1   13                               Географія часу
2   13                         Туристична географія
3  584       рентгенівська спектроскопія поглинання
4  584  рентгенівська фото електронна спектроскопія

In [73]:
df_uk_red[df_uk_red['link_val']=='Москва ']

Empty DataFrame
Columns: [id, link_val]
Index: []

In [74]:
# article names
df_uk_name = pd.read_csv(PATH_TO_DATA+"ukwiki-" + data_time + "-id_name.csv", encoding='utf-8', sep="^")

print(df_uk_name.shape)
print(df_uk_name.columns)
df_uk_name.head()

(819212, 3)
Index(['id', 'title', 'length'], dtype='object')

    id             title  length
0    3  Головна сторінка    3197
1   13         Географія   16843
2  584              Атом   35112
3  585           Мільярд    1759
4  586              Ядро    8064

In [75]:
# find maximum id among blue links
max_id = np.max(df_uk_name['id'])

# find unique titles among red links, create df with

red_links = df_uk_red['link_val'].unique()

red_links_ids = pd.DataFrame({'title': red_links, 
                               'id': np.arange(max_id+1, len(red_links)+max_id+1)})

red_links_ids.head()

        id                                        title
0  2817993                           Географія розвитку
1  2817994                               Географія часу
2  2817995                         Туристична географія
3  2817996       рентгенівська спектроскопія поглинання
4  2817997  рентгенівська фото електронна спектроскопія

In [76]:
df_uk_red_ext = df_uk_red.merge(right = red_links_ids, left_on = 'link_val', right_on = 'title', how = 'right')
df_uk_red_ext = df_uk_red_ext[['id_x', 'link_val', 'id_y']]
df_uk_red_ext.columns = ['id_parent', 'red_link_name', 'red_link_id']
print(df_uk_red_ext.shape)
df_uk_red_ext.head()

(2872272, 3)

   id_parent                           red_link_name  red_link_id
0         13                      Географія розвитку      2817993
1         13                          Географія часу      2817994
2    1928599                          Географія часу      2817994
3         13                    Туристична географія      2817995
4        584  рентгенівська спектроскопія поглинання      2817996

In [77]:
df_uk_red_ext.to_csv(PATH_TO_DATA+'all_uk_redlinks_with_parent_ids.csv')

In [15]:
# Load uk-en correpondences
fn = PATH_TO_DATA+'20180920-langlinks_uk_en.csv'
df_link = pd.read_csv(fn,  encoding='UTF-8', quotechar='\'')
print(df_link.shape)
print(df_link.columns)
df_link.head()

(599612, 3)
Index(['ll_from', 'll_lang', 'll_title'], dtype='object')

   ll_from ll_lang                          ll_title
0  2112530      en  ! (The Dismemberment Plan album)
1  1366003      en                ! (disambiguation)
2  2141483      en                                !!
3   425480      en                               !!!
4   848226      en                     !Action Pact!

In [14]:
df_uk_red_ext = pd.read_csv(PATH_TO_DATA+'all_uk_redlinks_with_parent_ids.csv')
print(df_uk_red_ext.shape)
df_uk_red_ext.head()

(2872272, 4)

   Unnamed: 0  id_parent                           red_link_name  red_link_id
0           0         13                      Географія розвитку      2817993
1           1         13                          Географія часу      2817994
2           2    1928599                          Географія часу      2817994
3           3         13                    Туристична географія      2817995
4           4        584  рентгенівська спектроскопія поглинання      2817996

In [16]:
# add en correspondences to uk parent pages for red links
df_uk_red_corresp = df_uk_red_ext.merge(right = df_link, left_on = 'id_parent', right_on = 'll_from', how = 'left')
df_uk_red_corresp.head()

,Unnamed: 0,id_parent,red_link_name,red_link_id,ll_from,ll_lang,ll_title
0,0,13,Географія розвитку,2817993,13.0,en,Geography
1,1,13,Географія часу,2817994,13.0,en,Geography
2,2,1928599,Географія часу,2817994,1928599.0,en,Geography (disambiguation)
3,3,13,Туристична географія,2817995,13.0,en,Geography
4,4,584,рентгенівська спектроскопія поглинання,2817996,584.0,en,Atom

In [17]:
df_uk_red_corresp = df_uk_red_corresp[pd.notnull(df_uk_red_corresp['ll_from'])]
df_uk_red_corresp.head()

,Unnamed: 0,id_parent,red_link_name,red_link_id,ll_from,ll_lang,ll_title
0,0,13,Географія розвитку,2817993,13.0,en,Geography
1,1,13,Географія часу,2817994,13.0,en,Geography
2,2,1928599,Географія часу,2817994,1928599.0,en,Geography (disambiguation)
3,3,13,Туристична географія,2817995,13.0,en,Geography
4,4,584,рентгенівська спектроскопія поглинання,2817996,584.0,en,Atom

In [18]:
df_uk_red_corresp = df_uk_red_corresp[['id_parent','red_link_name', 'red_link_id', 'll_title']]

In [19]:
df_uk_red_corresp.to_csv(PATH_TO_DATA+'df_allukredlinks_withentitle.csv', header=True, index=False)

In [82]:
df_uk_red_corresp = df_uk_red_corresp[['id_parent','red_link_name', 'red_link_id']]
df_uk_red_corresp = df_uk_red_corresp.sort_values(by = 'red_link_id')
df_uk_red_corresp = df_uk_red_corresp.drop_duplicates(keep = 'first')
df_uk_red_corresp = df_uk_red_corresp.dropna()
df_uk_red_corresp

,id_parent,red_link_name,red_link_id
0,13,Географія розвитку,2817993
1,13,Географія часу,2817994
2,1928599,Географія часу,2817994
3,13,Туристична географія,2817995
4,584,рентгенівська спектроскопія поглинання,2817996
5,584,рентгенівська фото електронна спектроскопія,2817997
11,2328123,мезолімбічний шлях,2817999
10,1209913,мезолімбічний шлях,2817999
8,42037,мезолімбічний шлях,2817999
9,427773,мезолімбічний шлях,2817999
12,588,Клінічна біохімія,2818000
14,588,Токсикологічна хімія,2818001
15,588,Спектрохімія,2818002
16,588,Скринінг (мікробіологія),2818003
17,1453980,Скринінг (мікробіологія),2818003
21,2016653,Структурна хімія,2818004
20,203221,Структурна хімія,2818004
18,588,Структурна хімія,2818004
19,33581,Структурна хімія,2818004
22,588,Економія атомів,2818005
23,588,Каяндер Микола Миколайович,2818006
25,592,ценологія,2818007
27,592,Вікова анатомія,2818008
28,2556491,Вікова анатомія,2818008
29,592,Глікобіологія,2818009
30,2556491,Глікобіологія,2818009
31,592,Фізіологія грибів,2818010
32,2556491,Фізіологія грибів,2818010
34,2556491,Ценологія,2818011
33,592,Ценологія,2818011
...,...,...,...
2872210,2817048,Kościół Matki Bożej Częstochowskiej w Jabłowie,4372920
2872211,2817071,Ptasi Śpiew,4372921
2872212,2817071,Śnieżka,4372922
2872213,2817074,Kościół Chrystusa Króla w Borównie,4372923
2872214,2817085,zamek Rogowiec,4372924
2872215,2817100,Głuszyca,4372925
2872218,2817142,Ян Беннетт,4372928
2872219,2817142,Майкл Джонсон (футболіст),4372929
2872220,2817142,Джон Маккарті (футболіст),4372930
2872221,2817142,Мартін Оконнор,4372931
2872222,2817142,Данні Соннер,4372932
2872223,2817142,Джофф Горсфілд,4372933
2872224,2817142,Деле Адебола,4372934
2872225,2817142,Девід Голдсворт,4372935
2872235,2817260,Klasztor w Głębowicach,4372945
2872236,2817312,cukrownia,4372946
2872239,2817436,Lubiąż,4372949
2872240,2817455,Pałac w Żerkowie,4372950
2872246,2817560,Mirków (województwo dolnośląskie),4372956
2872247,2817605,Mirków (województwo dolnośląskie),4372956
2872248,2817567,Pasikurowice (przystanek kolejowy),4372957
2872255,2817605,Siedlec Trzebnicki,4372964
2872256,2817727,Spichlerz,4372965
2872259,2817809,Pałac w Świątnikach,4372968
2872265,2817879,Pałac w Krobielowicach,4372973
2872266,2817891,Ochotnicza Straż Pożarna,4372974
2872267,2817915,Kąty Wrocławskie,4372975
2872269,2817934,Bystrzyca (dopływ Odry),4372976
2872268,2817931,Bystrzyca (dopływ Odry),4372976
2872270,2817934,Pałac w Sadowicach,4372977

In [83]:
# for every red link calculate number of incoming links
df_red_links_most_common = df_uk_red_corresp['red_link_id'].value_counts().reset_index()
df_red_links_most_common.head()

     index  red_link_id
0  2863300          941
1  2969411          848
2  4169378          760
3  3060807          687
4  3512597          639

In [84]:
df_red_links_most_common.columns = ['red_link_id_', 'count']
df_red_links_most_common.head()

   red_link_id_  count
0       2863300    941
1       2969411    848
2       4169378    760
3       3060807    687
4       3512597    639

In [85]:
df_red_links_most_common = df_red_links_most_common[(df_red_links_most_common['count'] >= 25)]
df_red_links_most_common

      red_link_id_  count
0          2863300    941
1          2969411    848
2          4169378    760
3          3060807    687
4          3512597    639
5          2826629    502
6          2826628    502
7          2826630    502
8          2826631    495
9          2825668    474
10         2826632    454
11         2825773    449
12         2880131    442
13         2928367    379
14         2967923    370
15         3042485    361
16         3052631    352
17         3274320    351
18         3046063    345
19         3279801    339
20         3355391    330
21         2867615    329
22         3136418    318
23         2922136    309
24         3077186    300
25         2989493    294
26         3139444    288
27         2930666    269
28         3139738    269
29         3139188    268
...            ...    ...
3345       3576270     25
3346       3127667     25
3347       4174631     25
3348       3540255     25
3349       2831417     25
3350       4064929     25
3351       4066147     25
3352       3531397     25
3353       3255465     25
3354       3539308     25
3355       3584106     25
3356       4064377     25
3357       3210124     25
3358       3426086     25
3359       4256694     25
3360       4065523     25
3361       4065295     25
3362       3101255     25
3363       3333732     25
3364       4064889     25
3365       3161139     25
3366       2881625     25
3367       3019288     25
3368       4064931     25
3369       3355439     25
3370       3132604     25
3371       4064948     25
3372       4065253     25
3373       2929203     25
3374       3354251     25

[3375 rows x 2 columns]

In [86]:
result = df_uk_red_corresp.merge(right = df_red_links_most_common,
                                 left_on = 'red_link_id', right_on = 'red_link_id_', how = 'inner')

In [87]:
result

,id_parent,red_link_name,red_link_id,red_link_id_,count
0,2579654,Каунт Бейсі,2818114,2818114,43
1,2543496,Каунт Бейсі,2818114,2818114,43
2,2543162,Каунт Бейсі,2818114,2818114,43
3,2538289,Каунт Бейсі,2818114,2818114,43
4,2581857,Каунт Бейсі,2818114,2818114,43
5,2530258,Каунт Бейсі,2818114,2818114,43
6,2525341,Каунт Бейсі,2818114,2818114,43
7,2389752,Каунт Бейсі,2818114,2818114,43
8,2535297,Каунт Бейсі,2818114,2818114,43
9,2590135,Каунт Бейсі,2818114,2818114,43
10,2324216,Каунт Бейсі,2818114,2818114,43
11,2597205,Каунт Бейсі,2818114,2818114,43
12,2598275,Каунт Бейсі,2818114,2818114,43
13,2598513,Каунт Бейсі,2818114,2818114,43
14,2602651,Каунт Бейсі,2818114,2818114,43
15,2603382,Каунт Бейсі,2818114,2818114,43
16,2609343,Каунт Бейсі,2818114,2818114,43
17,2695892,Каунт Бейсі,2818114,2818114,43
18,2593875,Каунт Бейсі,2818114,2818114,43
19,2322728,Каунт Бейсі,2818114,2818114,43
20,2641395,Каунт Бейсі,2818114,2818114,43
21,2302820,Каунт Бейсі,2818114,2818114,43
22,625,Каунт Бейсі,2818114,2818114,43
23,2321031,Каунт Бейсі,2818114,2818114,43
24,36823,Каунт Бейсі,2818114,2818114,43
25,159088,Каунт Бейсі,2818114,2818114,43
26,202525,Каунт Бейсі,2818114,2818114,43
27,202608,Каунт Бейсі,2818114,2818114,43
28,202613,Каунт Бейсі,2818114,2818114,43
29,221479,Каунт Бейсі,2818114,2818114,43
...,...,...,...,...,...
177368,2816200,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177369,2816134,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177370,2816206,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177371,2816301,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177372,2816298,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177373,2816289,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177374,2816286,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177375,2816283,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177376,2816280,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177377,2816277,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177378,2816274,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177379,2816269,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177380,2816266,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177381,2816203,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177382,2816263,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177383,2816257,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177384,2816259,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177385,2816248,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177386,2816243,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177387,2816240,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177388,2816237,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177389,2816234,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177390,2816231,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177391,2816229,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177392,2816224,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177393,2816219,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177394,2816217,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177395,2816214,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177396,2816212,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115
177397,2816253,Свідницький повіт (Нижньосілезьке воєводство){...,4372900,4372900,115

In [88]:
result_red_links_uk = result['red_link_name'].unique()
df_result_red_links_uk = pd.DataFrame(result_red_links_uk, columns=['red_link_name'])

# save red links to file
df_result_red_links_uk.to_csv(PATH_TO_DATA+'df_sample_red_links_uk.csv', header=True, index=False)