In [1]:
import pandas as pd

%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(0, '/media/andrii/earth/Katia/CS_MasterThesis/Red_links_Project_for_Wiki_draft/py')
import utils

In [2]:
PATH_TO_DATA = '/media/andrii/earth/Katia/CS_MasterThesis/data/ukwiki/uk_red_links/'

In [3]:
df_redlinks_sample = pd.read_csv(PATH_TO_DATA+'ukredlinks_final.csv', sep='^')

print(df_redlinks_sample.shape)
df_redlinks_sample.head()

(3171, 13)

,red_link_name,ground truth,Proper Name,Person,Latin,BabelNet_results,Evaluation_BN,Remarks_BN,en_similar_by_incoming_links,Evaluation_incoming_links,Remarks_incoming_links,Levenshtein_results,Evaluation_Levenshtein
0,Каунт Бейсі,Count Basie,PN,Person,NaN,NaN,FN,NaN,"[(0.081, 'The Count Basie Story'), (0.076, 'Th...",FP,NaN,Count Basie,TP
1,аль-Каїм,"?? Al-Qa'im (town), Al-Qa'im (Cairo), Al-Qa'im...",PN,NaN,NaN,Al-Qa'im (caliph),FP,article in UK Wiki exists. Impossible to know ...,"[(0.031, 'Ahmad al-Muqtadir'), (0.03, 'Cai Xia...",FP,NaN,Glamis,FP
2,королева,"?? gyne, monarch, queen regnant, queen (chess)...",NaN,NaN,NaN,"gyne, monarch, queen regnant, queen (chess), T...",FP,right item not first in the list,"[(0.033, 'List of consorts of the monarch of I...",FP,NaN,Coronet,FP
3,Prentice Hall,Prentice Hall,PN,NaN,Latin,NaN,FN,NaN,"[(0.078, 'Chemical tanker'), (0.067, 'Break of...",FP,NaN,Prentice Hall,TP
4,Tokar.ua,NaN,PN,NaN,Latin,NaN,TN,NaN,"[(0.05, 'List of virtual communities with more...",FP,NaN,Tsarina,FP

In [4]:
print('PROPER NAMES STATISTICS')

df_proper_names = df_redlinks_sample[df_redlinks_sample['Proper Name']=='PN']

print()
print('Number of items', df_redlinks_sample.groupby('Proper Name').size()[0])
print('Fraction of items', df_redlinks_sample.groupby('Proper Name').size()[0]/len(df_redlinks_sample))
print()

print('METRICS\' RESULTS ON PROPER NAMES')
print()
print('BabelNet results')
utils.f1_score(df_proper_names['Evaluation_BN'], with_print=True)
print()
print('Incoming links similarity results')
utils.f1_score(df_proper_names['Evaluation_incoming_links'], with_print=True)
print()
print('Levenshtein edit distance results')
utils.f1_score(df_proper_names['Evaluation_Levenshtein'], with_print=True)

PROPER NAMES STATISTICS

Number of items 3063
Fraction of items 0.9659413434247871

METRICS' RESULTS ON PROPER NAMES

BabelNet results
FP = 12
TN = 312
TP = 475
FN = 2258
precision = 0.975
recall = 0.174
f1_score = 0.295

Incoming links similarity results
FP = 2034
TN = 0
TP = 1025
FN = 0
precision = 0.335
recall = 1.0
f1_score = 0.502

Levenshtein edit distance results
FP = 1577
TN = 0
TP = 1486
FN = 0
precision = 0.485
recall = 1.0
f1_score = 0.653

(0.485145282402873, 1.0, 0.6533304022862167)

In [5]:
print('TITLES IN LATIN SCRIPT STATISTICS')

df_latin = df_redlinks_sample[df_redlinks_sample['Latin']=='Latin']

print()
print('Number of items', df_latin.groupby('Proper Name').size()[0])
print('Fraction of items', df_latin.groupby('Proper Name').size()[0]/len(df_redlinks_sample))
print()

print('METRICS\' RESULTS ON TITLES IN LATIN')
print()
print('BabelNet results')
utils.f1_score(df_latin['Evaluation_BN'], with_print=True)
print()
print('Incoming links similarity results')
utils.f1_score(df_latin['Evaluation_incoming_links'], with_print=True)
print()
print('Levenshtein edit distance results')
utils.f1_score(df_latin['Evaluation_Levenshtein'], with_print=True)

TITLES IN LATIN SCRIPT STATISTICS

Number of items 977
Fraction of items 0.30810469883317565

METRICS' RESULTS ON TITLES IN LATIN

BabelNet results
FP = 7
TN = 27
TP = 463
FN = 485
precision = 0.985
recall = 0.488
f1_score = 0.653

Incoming links similarity results
FP = 730
TN = 0
TP = 256
FN = 0
precision = 0.26
recall = 1.0
f1_score = 0.412

Levenshtein edit distance results
FP = 257
TN = 0
TP = 731
FN = 0
precision = 0.74
recall = 1.0
f1_score = 0.85

(0.7398785425101214, 1.0, 0.8504944735311227)

In [6]:
print('NAMES OF PEOPLE STATISTICS')

df_person = df_redlinks_sample[df_redlinks_sample['Person']=='Person']

print()
print('Number of items', df_person.groupby('Proper Name').size()[0])
print('Fraction of items', df_person.groupby('Proper Name').size()[0]/len(df_redlinks_sample))
print()

print('METRICS\' RESULTS ON NAMES OF PEOPLE')
print()
print('BabelNet results')
utils.f1_score(df_person['Evaluation_BN'], with_print=True)
print()
print('Incoming links similarity results')
utils.f1_score(df_person['Evaluation_incoming_links'], with_print=True)
print()
print('Levenshtein edit distance results')
utils.f1_score(df_person['Evaluation_Levenshtein'], with_print=True)

NAMES OF PEOPLE STATISTICS

Number of items 968
Fraction of items 0.30526647745190794

METRICS' RESULTS ON NAMES OF PEOPLE

BabelNet results
FP = 1
TN = 32
TP = 12
FN = 923
precision = 0.923
recall = 0.013
f1_score = 0.025

Incoming links similarity results
FP = 471
TN = 0
TP = 498
FN = 0
precision = 0.514
recall = 1.0
f1_score = 0.679

Levenshtein edit distance results
FP = 336
TN = 0
TP = 633
FN = 0
precision = 0.653
recall = 1.0
f1_score = 0.79

(0.653250773993808, 1.0, 0.7902621722846442)

In [7]:
print('METRICS\' RESULTS ON THE WHOLE SAMPLE')

print()
print('Number of items', len(df_redlinks_sample))
print()

print('METRICS\' RESULTS ON THE WHOLE SAMPLE')
print()
print('BabelNet results')
utils.f1_score(df_redlinks_sample['Evaluation_BN'], with_print=True)
print()
print('Incoming links similarity results')
utils.f1_score(df_redlinks_sample['Evaluation_incoming_links'], with_print=True)
print()
print('Levenshtein edit distance results')
utils.f1_score(df_redlinks_sample['Evaluation_Levenshtein'], with_print=True)

METRICS' RESULTS ON THE WHOLE SAMPLE

Number of items 3171

METRICS' RESULTS ON THE WHOLE SAMPLE

BabelNet results
FP = 15
TN = 346
TP = 482
FN = 2319
precision = 0.97
recall = 0.172
f1_score = 0.292

Incoming links similarity results
FP = 2131
TN = 0
TP = 1036
FN = 0
precision = 0.327
recall = 1.0
f1_score = 0.493

Levenshtein edit distance results
FP = 1670
TN = 0
TP = 1501
FN = 0
precision = 0.473
recall = 1.0
f1_score = 0.643

(0.47335225480920845, 1.0, 0.6425513698630138)

### concurrent scores

In [8]:
df_concur = pd.read_csv(PATH_TO_DATA+'concurrent_links_evaluation.csv', sep='^')

print(df_concur.shape)
df_concur.head()

(3171, 11)

,pair_unique_id,red_link_name,candidate,red_link_cand,ground truth,true_label,BN_results,incoming_links_score,concurrent_links_score,levenstein_score,concurrent_links_evaluation
0,2482,Pachetra sagittigera,Oeneis,Pachetra sagittigera Oeneis,Pachetra sagittigera,False,0,0.009,0.05682,0.900,FP
1,4974,Panemeria tenebrata,Oeneis,Panemeria tenebrata Oeneis,Panemeria tenebrata,False,0,0.004,0.05585,0.842,FP
2,7466,Panolis flammea,Oeneis,Panolis flammea Oeneis,Pine beauty,False,0,0.009,0.05689,0.800,FP
3,9960,Panthea coenobita,Oeneis,Panthea coenobita Oeneis,Panthea coenobita,False,0,0.002,0.05716,0.824,FP
4,12448,Papestra biren,Oeneis,Papestra biren Oeneis,Papestra biren,False,0,0.001,0.05697,0.857,FP

In [9]:
df_redlinks_sample_new = pd.merge(df_redlinks_sample, df_concur[['red_link_name','candidate', 'concurrent_links_evaluation']],
                                  on='red_link_name', how='left')

In [10]:
df_redlinks_sample_new

,red_link_name,ground truth,Proper Name,Person,Latin,BabelNet_results,Evaluation_BN,Remarks_BN,en_similar_by_incoming_links,Evaluation_incoming_links,Remarks_incoming_links,Levenshtein_results,Evaluation_Levenshtein,candidate,concurrent_links_evaluation
0,Каунт Бейсі,Count Basie,PN,Person,NaN,NaN,FN,NaN,"[(0.081, 'The Count Basie Story'), (0.076, 'Th...",FP,NaN,Count Basie,TP,Chris Albertson,FP
1,аль-Каїм,"?? Al-Qa'im (town), Al-Qa'im (Cairo), Al-Qa'im...",PN,NaN,NaN,Al-Qa'im (caliph),FP,article in UK Wiki exists. Impossible to know ...,"[(0.031, 'Ahmad al-Muqtadir'), (0.03, 'Cai Xia...",FP,NaN,Glamis,FP,Rhydderch ap Iestyn,FP
2,королева,"?? gyne, monarch, queen regnant, queen (chess)...",NaN,NaN,NaN,"gyne, monarch, queen regnant, queen (chess), T...",FP,right item not first in the list,"[(0.033, 'List of consorts of the monarch of I...",FP,NaN,Coronet,FP,Louise of Lorraine,FP
3,Prentice Hall,Prentice Hall,PN,NaN,Latin,NaN,FN,NaN,"[(0.078, 'Chemical tanker'), (0.067, 'Break of...",FP,NaN,Prentice Hall,TP,Port of Rijeka,FP
4,Tokar.ua,NaN,PN,NaN,Latin,NaN,TN,NaN,"[(0.05, 'List of virtual communities with more...",FP,NaN,Tsarina,FP,CarWings,FP
5,Monthly Notices of the Royal Astronomical Society,Monthly Notices of the Royal Astronomical Society,PN,NaN,Latin,Monthly Notices of the Royal Astronomical Society,TP,NaN,"[(0.035, 'Local group'), (0.034, 'Astrophysics...",FP,Right item present in the list,Monthly Notices of the Royal Astronomical Society,TP,OB star,FP
6,Світ (видавництво),NaN,PN,NaN,NaN,NaN,TN,NaN,"[(0.058, 'Our World In Data'), (0.044, 'Break ...",FP,NaN,Livingston,FP,List of continents by population,FP
7,Дубович Іван Андрійович,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.061, 'Our World In Data'), (0.046, 'Break ...",FP,NaN,Dutch Canadians,FP,Utsjoki,FP
8,помірні повітряні маси,NaN,NaN,NaN,NaN,NaN,TN,NaN,"[(0.037, 'Color term'), (0.035, 'Gennady Nevel...",FP,NaN,Robin Hood's Bay,FP,Varangerfjord,FP
9,Доповідь про торгівлю людьми,Trafficking in Persons Report,PN,NaN,NaN,NaN,FN,NaN,"[(0.134, 'Our World In Data'), (0.06, 'Ageing ...",FP,NaN,Romani people in Bulgaria,FP,Our World In Data,FP
10,Управління з моніторингу та боротьби з торгівл...,NaN,PN,NaN,NaN,NaN,TN,NaN,"[(0.134, 'Our World In Data'), (0.06, 'Ageing ...",FP,NaN,Polish minority in the Czech Republic,FP,Our World In Data,FP
11,Управління з моніторингу та боротьби з торгівл...,Office to Monitor and Combat Trafficking in Pe...,PN,NaN,NaN,NaN,FN,Title doesn't express that it is an office in USA,"[(0.123, 'Our World In Data'), (0.055, 'Ageing...",FP,NaN,Province of the Episcopal Church of South Sudan,FP,Our World In Data,FP
12,Руденко Ірина Станіславівна,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.053, 'Our World In Data'), (0.042, 'Break ...",FP,NaN,Regional airline,FP,Utsjoki,FP
13,Радченко Вероніка Вікторівна,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.053, 'Our World In Data'), (0.042, 'Break ...",FP,NaN,Yuen Long District,FP,Utsjoki,FP
14,Вакуленко Олена Володимирівна,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.053, 'Our World In Data'), (0.042, 'Break ...",FP,NaN,Greeks in Romania,FP,Utsjoki,FP
15,Скуратович Олег Ярославович,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.056, 'Our World In Data'), (0.043, 'Break ...",FP,NaN,Maurice de Hirsch,FP,Utsjoki,FP
16,Чанцева Ніна Іванівна,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.061, 'Our World In Data'), (0.045, 'Break ...",FP,NaN,Chinese Canadians,FP,Our World In Data,FP
17,Головне управління геодезії та картографії СРСР,NaN,PN,NaN,NaN,NaN,TN,NaN,"[(0.109, 'Our World In Data'), (0.049, 'Ageing...",FP,NaN,Color Line (ferry operator),FP,Our World In Data,FP
18,Random House,Random House,PN,NaN,Latin,Random House,TP,NaN,"[(0.035, 'Queen Rocks'), (0.035, 'Agora SA'), ...",FP,NaN,Random House,TP,The White Dragon (novel),FP
19,Simon & Schuster,Simon & Schuster,PN,NaN,Latin,NaN,FN,NaN,"[(0.038, 'The Years of Rice and Salt'), (0.037...",FP,NaN,Simon & Schuster,TP,James Frenkel,FP
20,Панчакутек Юпанкі,Pachacuti,PN,Person,NaN,NaN,FN,article in UK Wiki exists Інка Пачакутек Юпанк...,"[(0.036, 'Zhu Quan'), (0.036, 'Liverpool Castl...",FP,NaN,Zhu Quan,FP,Abd al-Haqq II,FP
21,Земун,"?? FK Zemun, Zemun",PN,NaN,NaN,"FK Zemun, Zemun",FP,right item not first in the list,"[(0.036, 'Hannes Trautloft'), (0.033, 'Nova Cr...",FP,Right item present in the list,Zemun,FP,Syrmia County,FP
22,Східний тюркський каганат,NaN,PN,NaN,NaN,NaN,FN,article in UK Wiki exists Східно-тюркський каг...,"[(0.063, 'Shahin Vahmanzadegan'), (0.057, 'Mel...",FP,NaN,Saint Fursey,FP,Tardu,FP
23,Приморська Хорватія,Duchy of Croatia,PN,NaN,NaN,Duchy of Croatia,TP,article in UK Wiki exists,"[(0.083, 'Seisyllwg'), (0.08, 'Anarawd ap Rhod...",FP,NaN,Eastern Arabia,FP,Ermengard of Italy,FP
24,Раштакурти,NaN,PN,NaN,NaN,NaN,TN,NaN,"[(0.241, 'Ten Kingdoms'), (0.063, 'Bruno the G...",FP,NaN,Ramsbury,FP,Wang Rong (warlord),FP
25,моніторинг,monitoring (medicine),NaN,NaN,NaN,monitoring (medicine),FP,NaN,"[(0.02, 'Seismic hazard'), (0.014, 'Ultramarin...",FP,NaN,Biomonitoring,FP,Salt gland,FP
26,Купрієнко Сергій Анатолійович,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.06, 'Inca Civil War'), (0.046, 'INTI Inter...",FP,NaN,Current Anthropology,FP,Sapote,FP
27,Талах Віктор Миколайович,NaN,PN,Person,NaN,NaN,TN,NaN,"[(0.086, 'Inca Civil War'), (0.063, 'Classic M...",FP,NaN,Classic Maya language,FP,Bloodletting in Mesoamerica,FP
28,Керкраде,Kerkrade,PN,NaN,NaN,NaN,FN,online BN found – TP,"[(0.048, 'Yannis Anastasiou'), (0.047, 'Robert...",FP,Right item present in the list,Kerkrade,TP,De Klassieker,FP
29,Daylight saving time,Daylight saving time,NaN,NaN,Latin,NaN,FN,“No result found for Daylight saving time in U...,"[(0.23, 'Treemapping'), (0.075, 'White Hispani...",FP,NaN,Walt Minnick,FP,United States territorial court,FP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3141,Ніколе Мунс-Ягерман,Nicole Muns-Jagerman,PN,Person,NaN,NaN,FN,NaN,"[(0.172, 'Nicole Muns-Jagerman'), (0.132, 'Sil...",TP,NaN,Nicole Muns-Jagerman,TP,Karen Schimper,FP
3142,Андреа Леанд,Andrea Leand,PN,Person,NaN,NaN,FN,NaN,"[(0.235, 'Andrea Leand'), (0.125, 'Leigh-Anne ...",TP,NaN,Andrea Leand,TP,Amanda Grunfeld,FP
3143,Беверлі Бовіс,Beverly Bowes,PN,Person,NaN,NaN,FN,NaN,"[(0.343, 'Beverly Bowes'), (0.161, 'Michelle T...",TP,NaN,Beverly Bowes,TP,Karen Schimper,FP
3144,Сенді Коллінз (тенісистка),Sandy Collins (tennis),PN,Person,NaN,NaN,FN,NaN,"[(0.118, 'Dana Gilbert'), (0.101, 'Sandy Colli...",FP,Right item present in the list,Sandy Collins (tennis),TP,Karen Schimper,FP
3145,Луїс Аллен (тенісистка),Louise Allen (tennis),PN,Person,NaN,NaN,FN,NaN,"[(0.312, 'Louise Allen (tennis)'), (0.167, 'Ca...",TP,NaN,Louise Allen (tennis),TP,Karen Schimper,FP
3146,Лаура Аррая,Laura Arraya,PN,Person,NaN,NaN,FN,NaN,"[(0.176, 'Jenny Klitch'), (0.151, 'Laura Array...",FP,Right item present in the list,Laura Arraya,TP,Karen Schimper,FP
3147,С'юзен Слоун,Susan Sloane,PN,Person,NaN,NaN,FN,NaN,"[(0.484, 'Susan Sloane'), (0.161, 'Halle Cioff...",TP,NaN,Susan Sloane,TP,Karen Schimper,FP
3148,Пінат Луї Гарпер,Peanut Louie Harper,PN,Person,NaN,NaN,FN,NaN,"[(0.173, 'Susan Sloane'), (0.155, 'Peanut Loui...",FP,Right item present in the list,Peanut Louie Harper,TP,Karen Schimper,FP
3149,Пілар Васкес,Pilar Vásquez,PN,Person,NaN,NaN,FN,NaN,"[(0.145, 'Shelley Solomon'), (0.142, 'Vicki Ne...",FP,NaN,Pam Casale,FP,Shelley Solomon,FP
3150,Ху На,Hu Na,PN,Person,NaN,NaN,FN,NaN,"[(0.318, 'Hu Na'), (0.2, 'Karen Schimper'), (0...",TP,NaN,Hu Na,TP,Shelley Solomon,FP
3151,Кім Стейнмец,Kim Steinmetz,PN,Person,NaN,NaN,FN,NaN,"[(0.245, 'Kim Steinmetz'), (0.139, 'Jenny Klit...",TP,NaN,Kim Steinmetz,TP,Karen Schimper,FP
3152,Пем Кеселі,Pam Casale,PN,Person,NaN,NaN,FN,NaN,"[(0.281, 'Pam Casale'), (0.184, 'Jenny Klitch'...",TP,NaN,Pam Casale,TP,Shelley Solomon,FP
3153,Ліса Бондер,Lisa Bonder,PN,Person,NaN,NaN,FN,NaN,"[(0.279, 'Lisa Bonder'), (0.154, 'Jenny Klitch...",TP,NaN,Lisa Bonder,TP,WTA Tour Championships appearances,FP
3154,Іноуе Ецуко,Etsuko Inoue,PN,Person,NaN,NaN,FN,NaN,"[(0.325, 'Etsuko Inoue'), (0.182, 'Tina Mochiz...",TP,NaN,Anne Minter,FP,Karen Schimper,FP
3155,Ева Крапль,Eva Krapl,PN,Person,NaN,NaN,FN,NaN,"[(0.317, 'Eva Krapl'), (0.167, 'Stacey Martin'...",TP,NaN,Eva Krapl,TP,Karen Schimper,FP
3156,Сабрина Голеш,Sabrina Goleš,PN,Person,NaN,NaN,FN,NaN,"[(0.208, 'Laura Lapi'), (0.202, 'Federica Bons...",FP,NaN,Sara Gomer,FP,Karen Schimper,FP
3157,Террі Фелпс,Terry Phelps,PN,Person,NaN,NaN,FN,NaN,"[(0.314, 'Terry Phelps'), (0.189, 'Michelle To...",TP,NaN,Terry Phelps,TP,WTA Tour Championships appearances,FP
3158,Селін Коен,Céline Cohen,PN,Person,NaN,NaN,FN,NaN,"[(0.203, 'Laura Lapi'), (0.159, 'Luciana Corsa...",FP,NaN,Helen Kelesi,FP,Karen Schimper,FP
3159,Венді Вайт (тенісистка),Wendy White (tennis),PN,Person,NaN,NaN,FN,NaN,"[(0.239, 'Wendy White (tennis)'), (0.128, 'Ter...",TP,NaN,Wendy White (tennis),TP,Karen Schimper,FP
3160,Тіна Мочідзукі,Tina Mochizuki,PN,Person,NaN,NaN,FN,NaN,"[(0.394, 'Tina Mochizuki'), (0.135, 'Debbie Sp...",TP,NaN,Tina Mochizuki,TP,Karen Schimper,FP
3161,Нейже Діас,Niege Dias,PN,Person,NaN,NaN,FN,NaN,"[(0.297, 'Niege Dias'), (0.164, 'Laura Lapi'),...",TP,NaN,Niege Dias,TP,Karen Schimper,FP
3162,Карен Шимпер,Karen Schimper,PN,Person,NaN,NaN,FN,NaN,"[(0.418, 'Karen Schimper'), (0.177, 'Elly Haka...",TP,NaN,Karen Schimper,TP,Karen Schimper,TP
3163,Мішелл Торрес,Michelle Torres,PN,Person,NaN,NaN,FN,NaN,"[(0.418, 'Michelle Torres'), (0.161, 'Karen Sc...",TP,NaN,Michelle Torres,TP,Karen Schimper,FP
3164,Лі Антонопліс,Lea Antonoplis,PN,Person,NaN,NaN,FN,NaN,"[(0.163, 'Lea Antonoplis'), (0.133, 'Vicki Nel...",TP,NaN,Lea Antonoplis,TP,Karen Schimper,FP
3165,Мері-Лу П'ятек,Mary-Lou Daniels,PN,Person,NaN,NaN,FN,NaN,"[(0.153, 'Michelle Torres'), (0.141, 'Mary-Lou...",FP,Right item present in the list,Mary-Lou Daniels,TP,Karen Schimper,FP
3166,Патрісія Медрадо,Patricia Medrado,PN,Person,NaN,NaN,FN,NaN,"[(0.182, 'Patricia Medrado'), (0.156, 'Dana Gi...",TP,NaN,Patricia Medrado,TP,Karen Schimper,FP
3167,С'юзен Маскарін,Susan Mascarin,PN,Person,NaN,NaN,FN,NaN,"[(0.271, 'Susan Mascarin'), (0.191, 'Vicki Nel...",TP,NaN,Susan Mascarin,TP,Karen Schimper,FP
3168,Алісія Молтон,Alycia Moulton,PN,Person,NaN,NaN,FN,NaN,"[(0.174, 'Alycia Moulton'), (0.145, 'Leigh-Ann...",TP,NaN,Alycia Moulton,TP,Karen Schimper,FP
3169,Сабіна Сіммондс,Sabina Simmonds,PN,Person,NaN,NaN,FN,NaN,"[(0.255, 'Sabina Simmonds'), (0.196, 'Leigh-An...",TP,NaN,Sabina Simmonds,TP,Marjorie Blackwood,FP
3170,Latin Rite,Roman Rite,NaN,NaN,Latin,NaN,FN,NaN,"[(0.066, 'List of Catholic dioceses in Spain, ...",FP,NaN,Retroquire,FP,Diego de Covarubias y Leyva,FP

In [11]:
df_person = df_redlinks_sample_new[df_redlinks_sample_new['Person']=='Person']

print('Concurrent link results on person subsample')
utils.f1_score(df_person['concurrent_links_evaluation'], with_print=True)
print()
print()

df_latin = df_redlinks_sample_new[df_redlinks_sample_new['Latin']=='Latin']

print('Concurrent link results on latin script subsample')
utils.f1_score(df_latin['concurrent_links_evaluation'], with_print=True)
print()
print()

df_proper_name = df_redlinks_sample_new[df_redlinks_sample_new['Proper Name']=='PN']

print('Concurrent link results on proper nouns subsample')
utils.f1_score(df_proper_name['concurrent_links_evaluation'], with_print=True)
print()
print()
print('Concurrent link results on the whole sample')
utils.f1_score(df_redlinks_sample_new['concurrent_links_evaluation'], with_print=True)
print()

Concurrent link results on person subsample
FP = 965
TN = 0
TP = 4
FN = 0
precision = 0.004
recall = 1.0
f1_score = 0.008


Concurrent link results on latin script subsample
FP = 986
TN = 0
TP = 2
FN = 0
precision = 0.002
recall = 1.0
f1_score = 0.004


Concurrent link results on proper nouns subsample
FP = 2999
TN = 0
TP = 64
FN = 0
precision = 0.021
recall = 1.0
f1_score = 0.041


Concurrent link results on the whole sample
FP = 3106
TN = 0
TP = 65
FN = 0
precision = 0.02
recall = 1.0
f1_score = 0.04